Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -29,41 +29,36 @@ jobs:
           sudo apt install -y autoconf libtool
           sudo apt-get install -y autoconf libtool m4
           sudo apt-get update
-          sudo apt-get install -y \
-            autoconf=2.69-11 \
-            automake=1:1.16.1-4 \
-            libtool=2.4.6-14 \
-            gettext
-            libtinfo6
+          sudo apt-get install libtinfo6
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           pip install buildozer
           pip install cython
 
-      # - name: Check version
-      #   run: |
+      - name: Check version
+        run: |
   
-      #     echo "Проверяем PATH"
+          echo "Проверяем PATH"
           
-      #     echo "PATH: $PATH"
-      #     if ! which libtool; then
-      #       echo "libtool not found in PATH, adding /usr/bin"
-      #       export PATH=$PATH:/usr/bin
-      #       echo "Updated PATH: $PATH" #Проверка, что PATH обновился.
-      #     fi
+          echo "PATH: $PATH"
+          if ! which libtool; then
+            echo "libtool not found in PATH, adding /usr/bin"
+            export PATH=$PATH:/usr/bin
+            echo "Updated PATH: $PATH" #Проверка, что PATH обновился.
+          fi
           
-      #     echo "Устанавливаем autoconf"
-      #     sudo apt install -y autoconf
-      #     echo "Скачиваем libtool"
-      #     sudo apt-get install -y libtool
-      #     echo "Проверяем, действительно ли скачался"
-      #     dpkg -l | grep libtool
-      #     echo "Смотрим, где находятся файлы libtool"
-      #     dpkg -L libtool
-      #     sudo ln -s /usr/bin/libtoolize /usr/bin/libtool
-      #     ls -l /usr/bin/libtool
-      #     autoconf --version
-      #     libtool --version
+          echo "Устанавливаем autoconf"
+          sudo apt install -y autoconf
+          echo "Скачиваем libtool"
+          sudo apt-get install -y libtool
+          echo "Проверяем, действительно ли скачался"
+          dpkg -l | grep libtool
+          echo "Смотрим, где находятся файлы libtool"
+          dpkg -L libtool
+          sudo ln -s /usr/bin/libtoolize /usr/bin/libtool
+          ls -l /usr/bin/libtool
+          autoconf --version
+          libtool --version
 
       # Step 4: Install Android dependencies
       - name: Install Android dependencies
